### ISSUE TITLE
make test runnable for anyone with linux system.

### ISSUE THREAD

**Issue by meijies** [tensorbase/tensorbase#42]
+ test with absolute data path, which causes test failed for others. 
   we should use relative data path or use /tmp directory which exists any linux system.
+ test with data which isn't exists at this repository.

**Comment by jinmingjian** [comment]
yes. Issue #28 wants to solve this. Not sure you are interesting to help:)

There are hard coded early-phase tests (this is bad) when the functionalities are not fully available.

Data path is a basic config parameter for TensorBase because TensorBase are a persistence-first design. We do not repeat the CH's tons of engine designs. (You may give some thoughts why this is good or bad before we happen to talk this exactly.)

more specifically: 

  > we should use relative data path or use /tmp directory which exists any linux system.

Relative data path to current repo seem better, for example, gen a $REPO_ROOT$/test_data. Then all tests use this dir. You can refer to test_utils::prepare_empty_tmp_dir.

> test with data which isn't exists at this repository.

we should generate the data when necessary.  One half an example is [runtime::write::unit_tests](https://github.com/tensorbase/tensorbase/blob/main/crates/runtime/src/write.rs). Some tests with heavy data dependency should move to integ tests( in every crates' tests or in common [tests_integ](https://github.com/tensorbase/tensorbase/tree/main/crates/tests_integ) ).

This is also a great opportunity for you to understand the working of TB when the tests tidying. I'd like to provide any help if you are further exploring:)

thanks for reporting!

**Comment by meijies** [comment]
> we should generate the data when necessary. One half an example is runtime::write::unit_tests. Some tests with heavy data dependency should move to integ tests( in every crates' tests or in common tests_integ )

Yes, I think it's time to re-organize the test cases, I'm not very familiar with to rust and database, but I can do a try.

**Comment by meijies** [comment]
even if the user don't specify the conf path, the server should be able to run with default conf. current the default conf load from ```env::current_exe()```/conf/base.conf, but ```env::current_exe``` is not fixed for diffreent cartes. which resulted in we have to put serveral simillar conf file to different cartes. so i think it's better to move conf file to  $BASE_ROOT$/conf. for developing, the $BASE_ROOT$ default be setted as same as  $REPO_ROOT$. 

the test_integ should load conf from $BASE_ROOT$/conf too, because i guess there is no extra config needed for test and they can share same data folders .

the default conf  file may as blew and I prefer to use relative path to $BASE_ROOT$
``` conf
[system]
meta_dirs = ["data/tb_schema"]
data_dirs = ["data/tb_data"]

[storage]
data_dirs_clickhouse = ""

[server]
ip_addr = "localhost"
port = 9528
```

**Comment by jinmingjian** [comment]
Hi, @meijies basically, your idea is great! 

The current design has following concerns:

1. (Data Privacy) Do not write any data to user's disk silently. 
    + This database side application, it definitely will write data to disks. So, It is better to let users to explicitly specify data writing locations. And currently we can run without conf does not mean that in the future we can run without conf. 
    + However, as your said, it is still a little verbose at least for now. I suggest we can add a startup parameter, such as "--demo" to try to use a default conf.

2. POLA(Principle of least astonishment). 
    + If we enable a relative path in the conf, the users and developers will ask "what relative to". As you seen, "the relative" root for users and for developers are not different. This makes the same conf has different meaning in different context. This is an unnecessary surprise! 
   + the conf for kinds of tests are unnecessarily centralized because tests are for kinds of scenarios. It is light and nice to have a self-working and decentralized setup.
   + all data writing tests are considering "heavy" tests. To solve for your concern, I suggest two possible ways: 
      * adding a common method to test_utils, all tests want data writing, call this method. This is preferred in that we do not introduce any magic.
      * adding a pre-defined config var, like $BASE_DEV_ROOT$ to $repo_root$/test_data.

Do you think so?:)

**Comment by jinmingjian** [comment]
we have made the tests runnable now. I close this issue for the long time inactive status. Thanks for all the discussion.
